# Generated by Django 5.2.12 on 2026-04-02 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_veiculo_acessorios_veiculo_acessorios'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='veiculo',
            options={'verbose_name': 'veículo', 'verbose_name_plural': 'veículos'},
        ),
        migrations.AlterField(
            model_name='modelo',
            name='categoria',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='marca',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
